version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - uvicorn
      - api:main
      - --host=0.0.0.0
      - --workers=2
      - --reload
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./
        target: /app/
      - type: bind
        source: ./data/
        target: /data/
        read_only: true
    restart: on-failure
